name: lytiks
description: "Lytiks - Control Inteligente de Plagas para el Agro"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  image_picker: ^1.0.7
  geolocator: ^11.0.0
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  sqflite: ^2.3.2
  sqflite_common_ffi: ^2.3.2
  path: ^1.9.0
  connectivity_plus: ^6.0.3
  http: ^1.2.1
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2
  encrypt: ^5.0.3
  workmanager: ^0.5.2
  permission_handler: ^11.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

# Configuración de íconos personalizados
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/logo2.png"
    background_color: "#004B63"
    theme_color: "#004B63"
  windows:
    generate: true
    image_path: "assets/images/logo2.png"
    icon_size: 48
  min_sdk_android: 21

# Assets de la aplicación
flutter:
  uses-material-design: true
  assets:
    - assets/images/
