name: Lytiks
description: "Lytiks - Control Inteligente de Plagas para el Agro"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.4
  geolocator: ^10.1.0
  flutter_map: ^6.1.0
  latlong2: ^0.9.1
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.0
  connectivity_plus: ^5.0.0
  http: ^1.1.0
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

# Configuración de íconos personalizados
flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/logo2.png"
    background_color: "#004B63"
    theme_color: "#004B63"
  windows:
    generate: true
    image_path: "assets/images/logo2.png"
    icon_size: 48
  min_sdk_android: 21

# Assets de la aplicación
flutter:
  uses-material-design: true
  assets:
    - assets/images/
